services:
  - type: web
    name: feedback-insight-hub
    env: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
