# Generated by Django 6.0.3 on 2026-04-10 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "access_mode",
                    models.CharField(
                        choices=[
                            ("login", "登入填寫"),
                            ("quick", "快捷收集"),
                            ("hybrid", "雙模式"),
                        ],
                        default="hybrid",
                        max_length=20,
                    ),
                ),
                ("thank_you_email_enabled", models.BooleanField(default=True)),
                ("improvement_tracking_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respondent_name", models.CharField(blank=True, max_length=120)),
                ("respondent_email", models.EmailField(blank=True, max_length=254)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("login", "登入填寫"),
                            ("quick", "快捷收集"),
                            ("hybrid", "雙模式"),
                        ],
                        default="quick",
                        max_length=20,
                    ),
                ),
                ("consent_follow_up", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="feedback.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("short_text", "短文"),
                            ("long_text", "長文"),
                            ("single_choice", "單選"),
                            ("multiple_choice", "多選"),
                            ("integer", "整數"),
                            ("decimal", "連續數值"),
                            ("scale", "量表"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("nominal", "名目"),
                            ("ordinal", "序位"),
                            ("discrete", "離散"),
                            ("continuous", "連續"),
                            ("text", "文字"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "options_text",
                    models.TextField(
                        blank=True, help_text="單選或多選使用，一行一個選項"
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("enable_keyword_tracking", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="feedback.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImprovementUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("related_category", models.CharField(blank=True, max_length=100)),
                ("send_global_notice", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvements",
                        to="feedback.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImprovementDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personalized_note", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="feedback.feedbacksubmission",
                    ),
                ),
                (
                    "improvement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="feedback.improvementupdate",
                    ),
                ),
            ],
            options={
                "unique_together": {("improvement", "submission")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="feedback.feedbacksubmission",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="feedback.question",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "question")},
            },
        ),
        migrations.CreateModel(
            name="KeywordCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("threshold", models.PositiveIntegerField(default=2)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_categories",
                        to="feedback.survey",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "keyword"],
                "unique_together": {("survey", "keyword")},
            },
        ),
    ]
