# Generated by Django 6.0.3 on 2026-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbacksubmission",
            name="source",
            field=models.CharField(
                choices=[
                    ("login", "登入後填答"),
                    ("quick", "快速填答"),
                    ("hybrid", "混合模式"),
                ],
                default="quick",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("nominal", "名目"),
                    ("ordinal", "順序"),
                    ("discrete", "離散"),
                    ("continuous", "連續"),
                    ("text", "文字"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("short_text", "短答"),
                    ("long_text", "長答"),
                    ("single_choice", "單選"),
                    ("multiple_choice", "多選"),
                    ("integer", "整數"),
                    ("decimal", "小數"),
                    ("scale", "量表"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="options_text",
            field=models.TextField(blank=True, help_text="選項題請一行填一個選項。"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("login", "登入後填答"),
                    ("quick", "快速填答"),
                    ("hybrid", "混合模式"),
                ],
                default="hybrid",
                max_length=20,
            ),
        ),
    ]
