# Generated by Django 6.0.3 on 2026-04-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedbacksubmission_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbacksubmission",
            name="source",
            field=models.CharField(
                choices=[
                    ("login", "登入後填答"),
                    ("quick", "免登入填答"),
                    ("hybrid", "混合模式"),
                ],
                default="quick",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("login", "登入後填答"),
                    ("quick", "免登入填答"),
                    ("hybrid", "混合模式"),
                ],
                default="hybrid",
                max_length=20,
            ),
        ),
    ]
