# Generated by Django 6.0.3 on 2026-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedbacksubmission_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="options_text",
            field=models.TextField(blank=True, help_text="每一行輸入一個選項。"),
        ),
    ]
