# Generated by Django 6.0.3 on 2026-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_alter_question_options_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbacksubmission",
            name="source",
            field=models.CharField(
                choices=[("login", "登入後填答")], default="login", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("short_text", "短文字"),
                    ("long_text", "長文字"),
                    ("single_choice", "單選"),
                    ("multiple_choice", "多選"),
                    ("integer", "整數"),
                    ("decimal", "小數"),
                    ("scale", "量表"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="options_text",
            field=models.TextField(
                blank=True, help_text="每行一個選項，供單選或多選題使用。"
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="access_mode",
            field=models.CharField(
                choices=[("login", "登入後填答")], default="login", max_length=20
            ),
        ),
    ]
