# Generated by Django 6.0.3 on 2026-04-21 07:33

from django.db import migrations


def convert_to_login(apps, schema_editor):
    Survey = apps.get_model("feedback", "Survey")
    FeedbackSubmission = apps.get_model("feedback", "FeedbackSubmission")
    Survey.objects.filter(access_mode__in=["quick", "hybrid"]).update(access_mode="login")
    FeedbackSubmission.objects.filter(source__in=["quick", "hybrid"]).update(source="login")


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0005_alter_feedbacksubmission_source_alter_question_kind_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(convert_to_login, migrations.RunPython.noop),
    ]
