# Generated by Django 6.0.3 on 2026-04-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_convert_access_mode_to_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="analysis_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="analysis_version",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
