# Generated by Django 6.0.3 on 2026-04-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_convert_access_mode_to_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "問卷分類",
                "verbose_name_plural": "問卷分類",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="survey",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to="feedback.surveycategory",
                verbose_name="分類",
            ),
        ),
    ]
