# Generated by Django 6.0.3 on 2026-04-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_add_survey_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbacksubmission",
            name="source",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="access_mode",
        ),
    ]
