# Generated by Django 6.0.3 on 2026-04-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_answer_analysis_text_answer_analysis_version_and_more"),
        ("feedback", "0008_remove_feedbacksubmission_source_and_more"),
    ]

    operations = []
