# Generated by Django 6.0.3 on 2026-05-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_merge_20260428_2314"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="analysis_text",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="analysis_version",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="sentiment_score",
        ),
    ]
