# Generated by Django 5.2.12 on 2026-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0011_remove_answer_analysis_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="analysis_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="analysis_version",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
