# Generated by Django 6.0.3 on 2026-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_notification_opt_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "顧客"), ("manager", "管理者")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
